apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        environment: prod
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service
          env:
            - name: APP_ENV
              value: prod
            - name: LOG_LEVEL
              value: INFO
            - name: MIGRATE_ON_START
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
              ephemeral-storage: 128Mi
