apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booking-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: booking-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: REPLACE_GSM_BOOKING_MONGODB_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: REPLACE_GSM_BOOKING_JWT_SECRET
