apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mongodb-external-secret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-mongodb-storage.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/booking-service
    newTag: a43e0c688c8ca7ff0ba844ca9a548fb448309bd6
