apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mongodb-external-secret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-mongodb-storage.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/booking-service
    newTag: 8d39e88db7d3a1fffc5634b3118c5b892d488384
