apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: phoenix-platform
data:
  PORT: "8084"
  NODE_ENV: development
  LOG_LEVEL: info
  BOOKING_SERVICE_BASE_URL: http://booking-service:8080
  USER_SERVICE_BASE_URL: http://user-service:8080
  CORS_ORIGIN: "*"
