apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: phoenix-platform
data:
  PORT: "8080"
  MONGODB_DATABASE: phoenix_inventory
  APP_CORS_ALLOWED_ORIGINS: https://dev.phoenix-project.online,https://phoenix-project.online
  ENVIRONMENT: development
  SERVICE_NAME: inventory-service
  LOG_LEVEL: info
  EVENT_SERVICE_URL: http://event-service:8081
  HOLD_TTL_MINUTES: "15"
  METRICS_ENABLED: "true"
  OTEL_SERVICE_NAME: inventory-service
  OTEL_TRACES_SAMPLER: "1.0"
  JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
  SERVICE_REGISTRY: '{"booking-service":["RESERVE_TICKET","VIEW_TICKET_INVENTORY"],"event-service":["CREATE_TICKET_TYPE","UPDATE_TICKET_INVENTORY","VIEW_TICKET_INVENTORY"]}'
