apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: event-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: event-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:  
        key: event-mongo-uri
    - secretKey: JWT_SECRET
      remoteRef:
        key: dev-jwt-secret
