apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        environment: dev
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - asia-south1-a
      containers:
        - name: event-service
          env:
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
