apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: phoenix-prod
  labels:
    app.kubernetes.io/part-of: phoenix-platform
    environment: prod
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: api.phoenix-project.online
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: phoenix-prod-gateway-tls
