apiVersion: v1
kind: ResourceQuota
metadata:
  name: phoenix-prod-quota
  namespace: phoenix-prod
  labels:
    app.kubernetes.io/part-of: phoenix-platform
    environment: prod
spec:
  hard:
    pods: "20"
    services: "20"
    persistentvolumeclaims: "8"
    requests.cpu: "3"
    requests.memory: 5Gi
    limits.cpu: "6"
    limits.memory: 10Gi
