apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: phoenix-platform
data:
  APP_NAME: user-service
  APP_PORT: "3000"
  APP_ENV: default
  JWT_ISSUER: phoenix-online-auth
  LOG_FORMAT: json
  FEATURE_USER_PROFILE_CACHE: "true"
  METRICS_ENABLED: "true"
  OTEL_SERVICE_NAME: user-service
  OTEL_TRACES_SAMPLER: "1.0"
  JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
