apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: phoenix-platform
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: collector-http
      port: 14268
      targetPort: collector-http
