apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-root-api
  labels:
    app.kubernetes.io/name: phoenix-root-api
    app.kubernetes.io/component: gateway-root
    app.kubernetes.io/part-of: phoenix-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: phoenix-root-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phoenix-root-api
        app.kubernetes.io/component: gateway-root
        app.kubernetes.io/part-of: phoenix-platform
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: http-echo
          image: hashicorp/http-echo:1.0.0
          args:
            - -listen=:8080
            - -text=phoenix ticketing api
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
              ephemeral-storage: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
