apiVersion: v1
kind: Service
metadata:
  name: phoenix-root-api
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"8080":{}}}'
  labels:
    app.kubernetes.io/name: phoenix-root-api
    app.kubernetes.io/component: gateway-root
    app.kubernetes.io/part-of: phoenix-platform
spec:
  selector:
    app.kubernetes.io/name: phoenix-root-api
  ports:
    - name: http
      port: 8080
      targetPort: http
