apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
patches:
  - path: patch-jaeger-deployment.yaml
  - path: patch-grafana-deployment.yaml
