apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: inventory-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: inventory_mongo_uri
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod-jwt-secret
