apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-prod
commonLabels:
  environment: prod
resources:
- ../../base
- external-secret.yaml
patches:
- path: patch-deployment.yaml
images:
- digest: sha256:0a36de4e4f068458f305639c08ffdcc4d5ed7605bb96e8fa82bec6d56e15095f
  name: ghcr.io/example-org/inventory-service
  newName: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/inventory-service
