apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-prod
commonLabels:
  environment: prod
resources:
  - ../../base
  - external-secret.yaml
patches:
  - path: patch-deployment.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/inventory-service
    newTag: 7feca20c5710016c3f9f19b31a8db7af67f2435f
