apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-service-mongodb-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: inventory-service-mongodb-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: mongo-root-passwd
