apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: prod
    spec:
      containers:
        - name: inventory-service
          env:
            - name: ENVIRONMENT
              value: production
            - name: LOG_LEVEL
              value: info
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
