apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mongodb-external-secret.yaml
patches:
  - path: patch-deployment.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/payment-service
    newTag: dev-latest
