apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mongodb-external-secret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-mongodb-storage.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/payment-service
    newTag: 7683b701ae2e02933ad142f656a2091bc7fc7a82
