apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: user-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: user-service-db-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: dev-jwt-secret
