apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mysql-external-secret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-mysql-storage.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/user-service
    newTag: 0a56415946b5a8c6dd3f7e4a9ae0727b3b5e3f5d
