apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phoenix-dev
commonLabels:
  environment: dev
resources:
  - ../../base
  - external-secret.yaml
  - mysql-external-secret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-mysql-storage.yaml
images:
  - name: asia-south1-docker.pkg.dev/phoenix-event-booking/phoenix-images/user-service
    newTag: e9dc3f54ca6f6bfe94ce17c6b5a51f8160a9087f
