apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-mysql-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: phoenix-gcp
    kind: ClusterSecretStore
  target:
    name: user-service-mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: user-service-mysql-password
