apiVersion: v1
kind: LimitRange
metadata:
  name: phoenix-dev-limits
  namespace: phoenix-dev
  labels:
    app.kubernetes.io/part-of: phoenix-platform
    environment: dev
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
